### ISSUE TITLE
Failed number generation

### ISSUE THREAD

**Issue by dr-orlovsky** [pandoraboxchain/lottery_algorithm#6]
Function fails here generating no random numbers. In which cases it can happen? We also need some failback mechanism here

https://github.com/pandoraboxchain/lottery_algorithm/blob/1aed9ba65561cf634a71c74b5436b41684830ab0/2.tests/inner_random/truf/contracts/Random.sol#L69

**Comment by Turtus** [comment]
thats my memory tricks on math statistics - all ok plz view https://github.com/pandoraboxchain/lottery_algorithm/blob/master/2.tests_r/readme.md
