### ISSUE TITLE
Test normality with alternative approach

### ISSUE THREAD

**Issue by dr-orlovsky** [pandoraboxchain/lottery_algorithm#7]
We need to generate Monte Carlo random number with standard computer algo and then compare them to random numbers from inner_contract with chi-square test. It will proof that our random generator is not worse then standard software random numbers, which are NOT TRUE randoms, but works well for the most of the tasks. Better then nothing :(

https://github.com/pandoraboxchain/lottery_algorithm/blob/1aed9ba65561cf634a71c74b5436b41684830ab0/3.r/script.R#L7

**Comment by Turtus** [comment]
shapiro gives correct random after box-muller on basic data, im happy)
